#k-neaarest neighbour alrgorthim is a supervised machine learning algorithm that is a classified technique that train the data by finding the distance from each point to the required point .

In [20]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

In [21]:
df=pd.read_csv("/content/Cancer_Data.csv")
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [23]:
df=df.drop(['id','Unnamed: 32'],axis=1)
df['diagnosis']=df['diagnosis'].replace({'M':1,'B':0})
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [24]:
X=df.iloc[:,1:]
y=df.iloc[:,0]

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [26]:
X_train.shape

(398, 30)

In [27]:
y_train.shape

(398,)

In [28]:
reg = KNeighborsClassifier() # default k value = 5
reg.fit(X_train , y_train)

KNeighborsClassifier()

**our data training is completed here the algorithm stores the values and and does the mathematical calculation when we do the predictions**

#Train performance
- to check the performace of the model we need to check the three categories.
1. confusion matrix
2. accuracy score
3. classification report

#confusion matrix- this is a measure that is used to analyse the classification performance
- when the model gives the output then it has 4possible ways.
- actual 1-predicted 1=tp
- actuall 0-predicted 0=tn
- actual 1-predicted 0=fn
- actual 0-predicted 1=fp

In [29]:
pred_answer=reg.predict(X_train)

In [30]:
training_data=pd.DataFrame()

training_data['answers']=y_train
training_data['predictions']=pred_answer
training_data

     answers  predictions
149        0            0
124        0            0
421        0            0
195        0            0
545        0            0
..       ...          ...
71         0            0
106        0            0
270        0            0
435        1            0
102        0            0

[398 rows x 2 columns]

In [31]:
X_train.shape

(398, 30)

In [32]:
training_data['answers'].value_counts()
#actual ansewes

answers
0    249
1    149
Name: count, dtype: int64

In [33]:
training_data['predictions'].value_counts()

predictions
0    264
1    134
Name: count, dtype: int64

#implementing confusion matrinx with out fn means using loops

In [34]:
tp=0
tn=0
fp=0
fn=0
for i in training_data.index:
  if training_data['answers'][i]==0 and training_data['predictions'][i]==0:
    tn=tn+1
  elif training_data['answers'][i]==1 and training_data['predictions'][i]==1:
     tp=tp+1
  elif training_data['answers'][i]==0 and training_data['predictions'][i]==1:
      fp=fp+1
  else:
      fn=fn+1

In [35]:
print(f"True positive {tp}")
print(f"True negative {tn}")
print(f"False positive {fp}")
print(f"False negative {fn}")

True positive 126
True negative 241
False positive 8
False negative 23

In [36]:
#with the built in fn
print(f"confusion matrix :{confusion_matrix(y_train,pred_answer)}")

confusion matrix :[[241   8]
 [ 23 126]]

# Accuracy - out of total positive outcomes how many are actually positive .
- this can be find using the values got buy the confusion matrix or by the built in fn called accuracy score.

In [37]:
accuracy=(tp+tn)/(tp+tn+fp+fn)

In [39]:
print(f"The accuract of the data is {accuracy}")

The accuract of the data is 0.9221105527638191

In [40]:
#with fn
print(f"accuracy score {accuracy_score(y_train,pred_answer)}")

accuracy score 0.9221105527638191

# calssification report
- this is the evaluation metrics or the model metrics for the classification so that we can know that how well our model is trained.
1. precision- out of total postive outcomes how many are actually correct is know as precision
- precision focuses on the predicted positive.
formula = tp/tp+fp
          tn/tn+fn
2. recall- focuses on the actual positive values.
formula=tp/tp+fn
3. f1-score- this metric is used to combine the precision and recall in a single vale if balances the model performance.
 formula= 2*p*r/p+r
 4. support- means no.of actual occurance of the class.

In [41]:
#with fn
print(f"Classification report {classification_report(y_train,pred_answer)}")

Classification report               precision    recall  f1-score   support

           0       0.91      0.97      0.94       249
           1       0.94      0.85      0.89       149

    accuracy                           0.92       398
   macro avg       0.93      0.91      0.92       398
weighted avg       0.92      0.92      0.92       398

# how to find the best k-value.
- when the accuracy of the data more for a particular k value then we can say that is a perfect value for our model.

In [48]:
k_value=np.arange(3,51,2)
li=[]
for i in k_value:
  mod=KNeighborsClassifier(n_neighbors=i)
  mod.fit(X_train,y_train)
  li.append(accuracy_score(y_train,mod.predict(X_train)))
li

[0.9472361809045227,
 0.9221105527638191,
 0.9346733668341709,
 0.9221105527638191,
 0.9221105527638191,
 0.9195979899497487,
 0.9195979899497487,
 0.9170854271356784,
 0.914572864321608,
 0.9120603015075377,
 0.9095477386934674,
 0.914572864321608,
 0.9095477386934674,
 0.9095477386934674,
 0.907035175879397,
 0.907035175879397,
 0.9095477386934674,
 0.907035175879397,
 0.9095477386934674,
 0.907035175879397,
 0.907035175879397,
 0.9095477386934674,
 0.907035175879397,
 0.907035175879397]

**we want to get the max value of the accuracy and for that we need the k value.**

In [53]:
print(k_value[li.index(max(li))])

3

#Test performance

In [56]:
X_test.shape

(171, 30)

In [58]:
y_test.value_counts()

diagnosis
0    108
1     63
Name: count, dtype: int64

In [57]:
y_test.shape

(171,)

In [54]:
print(confusion_matrix(y_test,reg.predict(X_test)))

[[107   1]
 [  6  57]]

In [59]:
print(accuracy_score(y_test,reg.predict(X_test)))

0.9590643274853801

In [60]:
print(classification_report(y_test,reg.predict(X_test)))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97       108
           1       0.98      0.90      0.94        63

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171

#my own data

In [64]:
n=np.random.random(30)
n

array([0.20138183, 0.55545926, 0.85146188, 0.63031179, 0.86926058,
       0.86161363, 0.45847828, 0.51448868, 0.0636238 , 0.09671181,
       0.9840605 , 0.70711967, 0.65719832, 0.95042858, 0.5598682 ,
       0.98182071, 0.11296314, 0.1395183 , 0.44092668, 0.84018964,
       0.36511661, 0.49810565, 0.44900316, 0.9032095 , 0.23067464,
       0.05035775, 0.20019506, 0.67892362, 0.39420214, 0.10863985])

In [67]:
result=reg.predict([[0.20138183, 0.55545926, 0.85146188, 0.63031179, 0.86926058,
       0.86161363, 0.45847828, 0.51448868, 0.0636238 , 0.09671181,
       0.9840605 , 0.70711967, 0.65719832, 0.95042858, 0.5598682 ,
       0.98182071, 0.11296314, 0.1395183 , 0.44092668, 0.84018964,
       0.36511661, 0.49810565, 0.44900316, 0.9032095 , 0.23067464,
       0.05035775, 0.20019506, 0.67892362, 0.39420214, 0.10863985]])[0]
if result==0:
  print(f"The patient has benin cancer")
else:
  print(f"The patient has malginine cancer")

np.int64(0)